export const products = [
    {
      name: 'Americano',
      image: 'https://picsum.photos/48',
      status: 'green',
      date: null,
    },
    {
      name: 'Espresso',
      image: 'https://picsum.photos/48',
      status: 'yellow',
      date: null,
    },
    {
      name: 'Mocha',
      image: '',
      status: 'green',
      date: null,
    },
    {
      name: 'White Mocha',
      image: '',
      status: 'yellow',
      date: 704305433,
    },
    {
      name: 'Latte',
      image: 'https://picsum.photos/48',
      status: 'green',
      date: 1666715033,
    },
    {
      name: 'Cappucino',
      image: 'https://picsum.photos/48',
      status: 'green',
      date: null,
    },
    {
      name: 'Walking with Giants',
      image: 'https://picsum.photos/48',
      status: 'green',
      date: null,
    },
    {
      name: 'Turbinator 2',
      image: 'https://picsum.photos/48',
      status: 'red',
      date: null,
    },
    {
      name: 'Super Cali Fragilistic Expialidocious',
      image: '',
      status: 'red',
      date: 704305433,
    },
    {
      name: 'Baseball Hat',
      image: 'https://picsum.photos/48',
      status: 'green',
      date: null,
    },
  {
      name: 'Americano',
      image: 'https://picsum.photos/48',
      status: 'green',
      date: null,
    },
    {
      name: 'Espresso',
      image: 'https://picsum.photos/48',
      status: 'yellow',
      date: null,
    },
    {
      name: 'Mocha',
      image: '',
      status: 'green',
      date: null,
    },
    {
      name: 'White Mocha',
      image: '',
      status: 'yellow',
      date: 704305433,
    },
    {
      name: 'Latte',
      image: 'https://picsum.photos/48',
      status: 'green',
      date: 1666715033,
    },
    {
      name: 'Cappucino',
      image: 'https://picsum.photos/48',
      status: 'green',
      date: null,
    },
    {
      name: 'Walking with Giants',
      image: 'https://picsum.photos/48',
      status: 'green',
      date: null,
    },
    {
      name: 'Turbinator 2',
      image: 'https://picsum.photos/48',
      status: 'red',
      date: null,
    },
    {
      name: 'Super Cali Fragilistic Expialidocious',
      image: '',
      status: 'red',
      date: 704305433,
    },
    {
      name: 'Baseball Hat',
      image: 'https://picsum.photos/48',
      status: 'green',
      date: null,
    },
  
  ]